-- AlterTable: add tracking fields to Lead
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "fbclid" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "gclid" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "fbp" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "fbc" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "eventId" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "landingPage" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "referrer" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "ipAddress" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "userAgent" TEXT;
ALTER TABLE "Lead" ADD COLUMN IF NOT EXISTS "consentMarketing" BOOLEAN NOT NULL DEFAULT false;

-- CreateIndex
CREATE UNIQUE INDEX IF NOT EXISTS "Lead_eventId_key" ON "Lead"("eventId");

-- CreateIndex
CREATE INDEX IF NOT EXISTS "Lead_eventId_idx" ON "Lead"("eventId");
