// Danh sách tỉnh/thành cho dropdown form đăng ký (lấy đúng thứ tự của form
// quatang.edu.vn — sắp theo vùng miền Bắc → Trung → Nam, KHÔNG phải A-Z).
// Chỉ là data hiển thị; lead lưu tên tỉnh dạng chuỗi trong `note`.

export const VN_PROVINCES = [
  "Hà Nội",
  "Hải Phòng",
  "Hải Dương",
  "Hưng Yên",
  "Hà Nam",
  "Nam Định",
  "Thái Bình",
  "Ninh Bình",
  "Hà Giang",
  "Cao Bằng",
  "Lào Cai",
  "Bắc Kạn",
  "Lạng Sơn",
  "Tuyên Quang",
  "Yên Bái",
  "Thái Nguyên",
  "Phú Thọ",
  "Vĩnh Phúc",
  "Bắc Giang",
  "Bắc Ninh",
  "Quảng Ninh",
  "Điện Biên",
  "Lai Châu",
  "Sơn La",
  "Hòa Bình",
  "Thanh Hóa",
  "Nghệ An",
  "Hà Tĩnh",
  "Quảng Bình",
  "Quảng Trị",
  "Huế",
  "Đà Nẵng",
  "Quảng Nam",
  "Quảng Ngãi",
  "Bình Định",
  "Phú Yên",
  "Khánh Hòa",
  "Kon Tum",
  "Gia Lai",
  "Đắk Lắk",
  "Đắk Nông",
  "Hồ Chí Minh",
  "Lâm Đồng",
  "Ninh Thuận",
  "Bình Phước",
  "Tây Ninh",
  "Bình Dương",
  "Đồng Nai",
  "Bình Thuận",
  "Bà Rịa - Vũng Tàu",
  "Long An",
  "Đồng Tháp",
  "An Giang",
  "Tiền Giang",
  "Vĩnh Long",
  "Bến Tre",
  "Kiên Giang",
  "Cần Thơ",
  "Hậu Giang",
  "Trà Vinh",
  "Sóc Trăng",
  "Bạc Liêu",
  "Cà Mau",
] as const;

/** Mặc định của form — trung tâm chỉ có cơ sở tại Đà Nẵng. */
export const VN_PROVINCE_DEFAULT = "Đà Nẵng";
