import * as XLSX from "xlsx";
import * as fs from "fs";
import * as path from "path";

interface Template {
  filename: string;
  sheetName: string;
  headers: string[];
  sampleRows: Record<string, string | number>[];
}

const TEMPLATES: Template[] = [
  {
    filename: "mau-demo.xlsx",
    sheetName: "Demo",
    headers: ["name", "email", "phone", "note"],
    sampleRows: [
      {
        name: "Nguyễn Văn A",
        email: "a@example.com",
        phone: "0901234567",
        note: "Demo 1",
      },
      {
        name: "Trần Thị B",
        email: "b@example.com",
        phone: "0907654321",
        note: "Demo 2",
      },
    ],
  },
  {
    filename: "mau-co-so.xlsx",
    sheetName: "Cơ sở",
    headers: [
      "name",
      "slug",
      "address",
      "ward",
      "district",
      "city",
      "phone",
      "email",
      "googleMapUrl",
      "workingHours",
      "managerName",
      "description",
      "isActive",
      "displayOrder",
    ],
    sampleRows: [
      {
        name: "Sata Robo Chi nhánh Đà Nẵng",
        slug: "danang",
        address: "258 Lê Thanh Nghị",
        ward: "Hòa Cường",
        district: "Hải Châu",
        city: "Đà Nẵng",
        phone: "0818823720",
        email: "danang@satarobo.vn",
        googleMapUrl: "https://maps.app.goo.gl/example",
        workingHours: "T2-T6: 17h-21h, T7-CN: 8h-17h",
        managerName: "Nguyễn Văn A",
        description: "Chi nhánh chính tại Đà Nẵng",
        isActive: 1,
        displayOrder: 1,
      },
      {
        name: "Sata Robo Chi nhánh Hà Nội",
        slug: "hanoi",
        address: "456 Trường Chinh",
        ward: "Phương Liệt",
        district: "Thanh Xuân",
        city: "Hà Nội",
        phone: "0901234567",
        email: "hanoi@satarobo.vn",
        googleMapUrl: "",
        workingHours: "T2-T6: 17h-21h, T7-CN: 8h-17h",
        managerName: "Trần Thị B",
        description: "",
        isActive: 1,
        displayOrder: 2,
      },
    ],
  },
  {
    filename: "mau-phong-hoc.xlsx",
    sheetName: "Phòng học",
    headers: [
      "name",
      "code",
      "centerSlug",
      "capacity",
      "equipment",
      "status",
      "notes",
      "displayOrder",
    ],
    sampleRows: [
      {
        name: "Phòng A1",
        code: "DN-A1",
        centerSlug: "danang",
        capacity: 15,
        equipment: "Robot SR1, Laptop, Máy chiếu",
        status: "ACTIVE",
        notes: "",
        displayOrder: 1,
      },
      {
        name: "Phòng A2",
        code: "DN-A2",
        centerSlug: "danang",
        capacity: 20,
        equipment: "Robot SR2, Bảng tương tác",
        status: "ACTIVE",
        notes: "",
        displayOrder: 2,
      },
    ],
  },
  {
    filename: "mau-lich-nghi.xlsx",
    sheetName: "Lịch nghỉ",
    headers: ["name", "date", "endDate", "centerSlug", "type", "note"],
    sampleRows: [
      {
        name: "Tết Dương lịch 2026",
        date: "2026-01-01",
        endDate: "",
        centerSlug: "",
        type: "HOLIDAY",
        note: "Nghỉ Tết Dương lịch",
      },
      {
        name: "Tết Nguyên Đán Bính Ngọ",
        date: "2026-02-17",
        endDate: "2026-02-23",
        centerSlug: "",
        type: "HOLIDAY",
        note: "Nghỉ Tết Nguyên Đán",
      },
      {
        name: "Bảo trì hệ thống điện",
        date: "2026-03-15",
        endDate: "",
        centerSlug: "danang",
        type: "MAINTENANCE",
        note: "Chỉ chi nhánh Đà Nẵng",
      },
      {
        name: "Lễ Quốc khánh",
        date: "2026-09-02",
        endDate: "2026-09-03",
        centerSlug: "",
        type: "HOLIDAY",
        note: "",
      },
    ],
  },
  {
    filename: "mau-hoc-vien.xlsx",
    sheetName: "Học viên",
    headers: [
      "studentCode",
      "fullName",
      "dateOfBirth",
      "gender",
      "currentGrade",
      "school",
      "parentName",
      "parentPhone",
      "parentEmail",
      "parentRelation",
      "parent2Name",
      "parent2Phone",
      "parent2Relation",
      "address",
      "ward",
      "district",
      "city",
      "centerSlug",
      "enrollmentDate",
      "status",
      "bloodType",
      "allergies",
      "healthNotes",
      "notes",
    ],
    sampleRows: [
      {
        studentCode: "SR-HV-001",
        fullName: "Nguyễn Văn An",
        dateOfBirth: "2018-03-15",
        gender: "MALE",
        currentGrade: 1,
        school: "Tiểu học Trần Văn Ơn",
        parentName: "Nguyễn Văn Bình",
        parentPhone: "0901234567",
        parentEmail: "nvb@gmail.com",
        parentRelation: "Bố",
        parent2Name: "Trần Thị Hoa",
        parent2Phone: "0907654321",
        parent2Relation: "Mẹ",
        address: "123 Hùng Vương",
        ward: "Phước Mỹ",
        district: "Sơn Trà",
        city: "Đà Nẵng",
        centerSlug: "danang",
        enrollmentDate: "2026-05-23",
        status: "ACTIVE",
        bloodType: "A_POS",
        allergies: "Tôm, sữa",
        healthNotes: "Bị hen suyễn nhẹ, cần lưu ý khi vận động",
        notes: "Đăng ký qua campaign 20 suất miễn phí 23/05",
      },
      {
        studentCode: "SR-HV-002",
        fullName: "Lê Thị Bình",
        dateOfBirth: "2014-08-20",
        gender: "FEMALE",
        currentGrade: 5,
        school: "",
        parentName: "Lê Văn Cường",
        parentPhone: "0912345678",
        parentEmail: "",
        parentRelation: "Bố",
        parent2Name: "",
        parent2Phone: "",
        parent2Relation: "",
        address: "",
        ward: "",
        district: "",
        city: "Đà Nẵng",
        centerSlug: "danang",
        enrollmentDate: "2026-05-24",
        status: "ACTIVE",
        bloodType: "",
        allergies: "",
        healthNotes: "",
        notes: "",
      },
      {
        studentCode: "SR-HV-003",
        fullName: "Trần Quốc Cường",
        dateOfBirth: "2011-12-05",
        gender: "MALE",
        currentGrade: 8,
        school: "THCS Nguyễn Du",
        parentName: "Trần Văn Minh",
        parentPhone: "0923456789",
        parentEmail: "tvm@yahoo.com",
        parentRelation: "Bố",
        parent2Name: "",
        parent2Phone: "",
        parent2Relation: "",
        address: "45 Lê Lợi",
        ward: "",
        district: "Hải Châu",
        city: "Đà Nẵng",
        centerSlug: "",
        enrollmentDate: "",
        status: "ACTIVE",
        bloodType: "UNKNOWN",
        allergies: "",
        healthNotes: "",
        notes: "Đăng ký walk-in tại event giới thiệu",
      },
    ],
  },
  {
    filename: "mau-nhan-vien.xlsx",
    sheetName: "Nhân viên",
    headers: [
      "employeeCode",
      "fullName",
      "jobTitle",
      "department",
      "status",
      "phone",
      "email",
      "dateOfBirth",
      "gender",
      "nationalId",
      "contractType",
      "centerSlug",
      "managerCode",
      "joinedAt",
      "endDate",
      "address",
      "subjects",
      "certifications",
      "bio",
      "emergencyContact",
      "notes",
    ],
    sampleRows: [
      {
        employeeCode: "SR.GV.001",
        fullName: "Nguyễn Văn A",
        jobTitle: "Giáo viên Robotics",
        department: "GIANG_DAY",
        status: "ACTIVE",
        phone: "0901234567",
        email: "nva@satarobo.vn",
        dateOfBirth: "1992-05-15",
        gender: "MALE",
        nationalId: "048092123456",
        contractType: "FULLTIME",
        centerSlug: "danang",
        managerCode: "",
        joinedAt: "2024-01-15",
        endDate: "",
        address: "12 Hùng Vương, Thạch Thang, Hải Châu, Đà Nẵng",
        subjects: "Robotics, RoboSim",
        certifications: "Robot Hardware Cert 2023",
        bio: "Giáo viên Robotics với 3 năm kinh nghiệm dạy học sinh lớp 1-8",
        emergencyContact: "Nguyễn Thị B - Vợ - 0907654321",
        notes: "",
      },
      {
        employeeCode: "SR.TV.001",
        fullName: "Trần Thị B",
        jobTitle: "Tư vấn tuyển sinh",
        department: "TUYEN_SINH",
        status: "ACTIVE",
        phone: "0912345678",
        email: "ttb@satarobo.vn",
        dateOfBirth: "1995-08-20",
        gender: "FEMALE",
        nationalId: "",
        contractType: "FULLTIME",
        centerSlug: "danang",
        managerCode: "",
        joinedAt: "2024-03-01",
        endDate: "",
        address: "45 Lê Lợi, Hải Châu, Đà Nẵng",
        subjects: "",
        certifications: "",
        bio: "",
        emergencyContact: "",
        notes: "",
      },
      {
        employeeCode: "SR.HR.001",
        fullName: "Lê Văn C",
        jobTitle: "Chuyên viên nhân sự",
        department: "HANH_CHANH_NHAN_SU",
        status: "ACTIVE",
        phone: "0923456789",
        email: "lvc@satarobo.vn",
        dateOfBirth: "1990-12-10",
        gender: "MALE",
        nationalId: "",
        contractType: "CHINH_THUC_KHONG_XAC_DINH",
        centerSlug: "",
        managerCode: "",
        joinedAt: "2023-06-01",
        endDate: "",
        address: "",
        subjects: "",
        certifications: "",
        bio: "",
        emergencyContact: "",
        notes: "",
      },
    ],
  },
];

const outDir = path.join(process.cwd(), "public", "templates");
fs.mkdirSync(outDir, { recursive: true });

for (const tpl of TEMPLATES) {
  const ws = XLSX.utils.json_to_sheet(tpl.sampleRows, { header: tpl.headers });
  const wb = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(wb, ws, tpl.sheetName);
  const filepath = path.join(outDir, tpl.filename);
  XLSX.writeFile(wb, filepath);
  console.log(`✅ ${filepath}`);
}
