// SINH TỰ ĐỘNG từ bộ md nguồn `satarobo-huongdan/sitephuhuynh`
// bằng script `_gen-content.mjs` (đặt cạnh bộ md nguồn). KHÔNG sửa tay file này —
// sửa md nguồn rồi chạy lại: node _gen-content.mjs
import type { PortalGuide } from "./types";

export const PORTAL_GUIDES: PortalGuide[] = [
  {
    "slug": "tong-quan-va-dang-nhap",
    "order": 0,
    "title": "Tổng quan & đăng nhập",
    "category": "Bắt đầu",
    "description": "Kích hoạt tài khoản, đăng nhập, bố cục màn hình, chuyển chế độ Phụ huynh ↔ Học sinh, đổi giao diện, đăng xuất.",
    "pagePath": "/portal",
    "body": "# 00. Tổng quan & đăng nhập\n\n> Áp dụng: toàn cổng phụ huynh · Đối tượng: phụ huynh có con đang học tại Sata Robo.\n\n## 1. Cổng phụ huynh là gì?\n\nCổng phụ huynh (`hocvien.satarobo.vn`) là nơi quý phụ huynh:\n\n- Theo dõi việc học của con: lịch học, điểm danh, nhận xét sau mỗi buổi, ảnh lớp, học bạ.\n- Xem học phí, công nợ, lịch sử đóng tiền.\n- Gửi yêu cầu tới trung tâm (xin nghỉ, học bù, hỏi đáp…) và nhận phản hồi.\n- Nhận thông báo, nhắn tin với trung tâm, trả lời khảo sát.\n- Vào **Cổng học sinh** để con làm bài tập, bài thi, xem buổi học.\n\n## 2. Kích hoạt tài khoản (lần đầu)\n\n1. Trung tâm tạo tài khoản và gửi **link kích hoạt** qua email/SĐT đã đăng ký.\n2. Mở link → nhập **mã OTP** → đặt **mật khẩu** → đăng nhập.\n3. Nếu chưa nhận được link hoặc tài khoản báo \"chưa được liên kết với học viên nào\" — liên hệ trung tâm để được hỗ trợ.\n\n## 3. Đăng nhập\n\n1. Vào **`hocvien.satarobo.vn`** (hoặc `satarobo.vn/login`).\n2. Nhập **email** và **mật khẩu** → bấm **Đăng nhập**.\n3. Hệ thống tự nhận diện tài khoản phụ huynh và đưa vào **trang Tổng quan**.\n\n💡 Quên mật khẩu: liên hệ trung tâm để được cấp lại.\n\n## 4. Bố cục màn hình\n\n### 4.1. Thanh menu bên trái (máy tính)\n\n12 mục của **chế độ Phụ huynh**: Tổng quan · Các con · Lịch học · Nhận xét · Hình ảnh lớp · Học bạ · Học phí & công nợ · Yêu cầu học bù · Khảo sát trung tâm · Thông báo · Tin nhắn · Hồ sơ. Mục đang mở được tô màu nổi bật; mục Thông báo/Tin nhắn có **chấm số đỏ** khi có nội dung chưa đọc.\n\n### 4.2. Thanh trên cùng\n\n- **Chip chuyển chế độ** (góc trái): ghi \"PHỤ HUYNH · 〈tên〉\". Bấm mở menu:\n  - **\"Chế độ Phụ huynh\"** — về cổng phụ huynh.\n  - Mục **\"Các con\"** — bấm tên một con để vào **Cổng học sinh** của con đó (xem bài [Cổng học sinh](/portal/huong-dan/cong-hoc-sinh)).\n- **Nút Sáng/Tối** — đổi giao diện.\n- **Chuông 🔔** — mở trang Thông báo; có số đỏ khi có thông báo mới.\n- **Avatar + tên** (góc phải) — menu tài khoản:\n  - **\"Hồ sơ liên lạc\"** — xem/cập nhật thông tin liên hệ.\n  - **\"Hướng dẫn sử dụng\"** — mở bộ hướng dẫn này.\n  - **\"Giao diện\"** — tùy chỉnh Sáng/Tối.\n  - **\"Đổi mật khẩu\"** — đổi mật khẩu (trong trang Hồ sơ).\n  - **\"Đăng xuất\"** (màu đỏ).\n\n### 4.3. Trên điện thoại\n\n- Menu chuyển xuống **thanh dưới cùng** với 4 mục hay dùng: Tổng quan · Lịch học · Học phí · Thông báo; các mục còn lại nằm trong nút **\"Thêm\"**.\n\n## 5. Nhà có nhiều con\n\n- Mỗi lúc cổng hiển thị dữ liệu của **một con đang chọn**. Đổi con bằng **chip chuyển chế độ** góc trên trái (chọn tên con trong mục \"Các con\").\n- Trang **Các con** (`/portal/ho-so-con`) xem nhanh hồ sơ tất cả các con.\n\n## 6. Đăng xuất\n\nBấm **avatar** góc phải → **\"Đăng xuất\"**.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Trang Tổng quan | [/portal](/portal) |\n| Đăng nhập | [/login](/login) |\n| Hồ sơ liên lạc | [/portal/ho-so](/portal/ho-so) |\n| Bộ hướng dẫn | [/portal/huong-dan](/portal/huong-dan) |"
  },
  {
    "slug": "trang-tong-quan",
    "order": 1,
    "title": "Trang Tổng quan",
    "category": "Bắt đầu",
    "description": "Bảng điều khiển của phụ huynh — việc cần xử lý, tình hình từng con, lịch học và thông báo mới.",
    "pagePath": "/portal",
    "body": "# 01. Trang Tổng quan\n\n> Trang: **Tổng quan** (`/portal`) — mục đầu tiên trong menu.\n\n## 1. Trang này dùng để làm gì?\n\nLà màn hình đầu tiên sau khi đăng nhập: tổng hợp **việc cần xử lý** (học phí, học bù, bài chưa nộp) và **tình hình học tập của tất cả các con** — bấm vào mục nào cũng đi thẳng tới trang chi tiết tương ứng.\n\n## 2. Các khu vực trên trang (từ trên xuống)\n\n### 2.1. Dải chào mừng\n\n\"Chào 〈tên phụ huynh〉 👋 — Đồng hành cùng 〈n〉 con tại SataRobo.\" Bên phải là ô **\"Việc cần xử lý\"** (số việc) — khi không có việc, ô đổi thành **\"Số con\"**.\n\n### 2.2. \"Cần bạn xử lý\"\n\nDanh sách thẻ việc, sinh tự động theo từng con:\n\n| Thẻ | Khi nào hiện | Bấm vào đi đâu |\n|---|---|---|\n| **\"Học phí chưa đóng\"** — 〈tên con〉 · 〈số tiền〉đ | Con còn công nợ | Trang Học phí |\n| **\"〈n〉 buổi cần học bù\"** | Con có buổi vắng chưa được xếp bù | Trang Yêu cầu (đăng ký học bù) |\n| **\"〈n〉 bài chưa nộp\"** | Con còn bài tập chưa nộp | Trang Bài tập |\n\nKhi mọi thứ ổn: dải xanh **\"Mọi việc đều ổn — không có khoản nào cần xử lý ngay.\"**\n\n### 2.3. \"Các con của bạn\"\n\nMỗi con một thẻ:\n\n- Tên + khóa · lớp (hoặc \"Chưa xếp lớp\").\n- Thanh **\"Tiến độ khóa học\"**: % + số buổi đã học/tổng.\n- 3 ô: **Chuyên cần** (%, xanh nếu ≥ 90%), **Bài chờ** (số bài chưa nộp), **Học phí** (\"Đủ\" xanh / \"Còn nợ\" vàng).\n- 2 nút: **\"Hồ sơ\"** và **\"Cổng học sinh\"** → mở trang Các con.\n\n### 2.4. Hai cột dưới\n\n- **\"Lịch học\"**: bấm **\"Xem lịch\"** → trang Lịch học.\n- **\"Thông báo\"**: 4 thông báo mới nhất; bấm **\"Tất cả\"** → trang Thông báo.\n\n## 3. Lưu ý\n\n- Trang này **gộp tất cả các con** — không phụ thuộc con đang chọn.\n- Công nợ chỉ tính các khoản đã được kế toán xác nhận; số liệu bài tập/chuyên cần cập nhật theo dữ liệu lớp.\n- Trang chỉ để xem và điều hướng — không có thao tác gửi/nhập nào ở đây.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Trang Tổng quan | [/portal](/portal) |\n| Xem học phí | [/portal/hoc-phi](/portal/hoc-phi) |\n| Đăng ký học bù / gửi yêu cầu | [/portal/yeu-cau](/portal/yeu-cau) |\n| Xem lịch học | [/portal/lich](/portal/lich) |\n| Xem thông báo | [/portal/thong-bao](/portal/thong-bao) |"
  },
  {
    "slug": "cac-con",
    "order": 2,
    "title": "Các con",
    "category": "Theo dõi con",
    "description": "Danh sách các con với tóm tắt nhanh; mở hồ sơ chi tiết từng con, sửa thông tin và bật/thu hồi đồng ý dùng hình ảnh.",
    "pagePath": "/portal/ho-so-con",
    "body": "# 02. Các con\n\n> Trang: **Các con** (`/portal/ho-so-con`) — menu trái.\n\n## 1. Trang này dùng để làm gì?\n\nXem **tất cả các con** cùng lúc, mỗi con một thẻ tóm tắt (tiến độ, chuyên cần, bài chờ, học phí, buổi kế tiếp), và là cửa vào **hồ sơ chi tiết** của từng con — nơi cập nhật thông tin và quản lý **đồng ý dùng hình ảnh**.\n\n## 2. Thẻ của mỗi con\n\n- Tên + \"Khóa · Lớp\" (hoặc \"Chưa xếp lớp\").\n- **\"Tiến độ khóa học\"**: % và số buổi đã học/tổng.\n- 4 ô: **Chuyên cần** (%, xanh nếu ≥ 90%) · **Bài chờ** (bài chưa nộp) · **Học phí** (\"Đủ\"/\"Còn nợ\") · **Buổi tiếp theo** (\"Hôm nay\"/\"Ngày mai\"/ngày).\n- Nút **\"Xem hồ sơ\"** → hệ thống chuyển con này thành **con đang chọn** rồi mở trang chi tiết.\n\n## 3. Hồ sơ chi tiết của con (`/portal/ho-so-con/chi-tiet`)\n\n### 3.1. Cập nhật thông tin (phụ huynh tự sửa)\n\nCard **\"Thông tin học viên\"** — sửa được: **Ngày sinh** · **Giới tính** · **Khối lớp (văn hoá)** · **Trường** · **Ghi chú sức khoẻ** · **Dị ứng** (cách nhau dấu phẩy) · **Ghi chú khác** → bấm **\"Lưu thay đổi\"** → \"Đã lưu hồ sơ con\".\n\n⚠️ **Mã học viên, lớp và khóa học do trung tâm quản lý** — phụ huynh không sửa được; cần điều chỉnh hãy liên hệ trung tâm.\n\n### 3.2. Đồng ý dùng hình ảnh (quan trọng)\n\nỞ đầu trang chi tiết, cạnh tên con:\n\n- Chưa đồng ý: badge vàng **\"Chưa đồng ý hình ảnh\"** + nút **\"Đồng ý dùng hình ảnh\"** — bấm 1 lần là bật, ảnh lớp của con bắt đầu hiển thị được.\n- Đã đồng ý: badge xanh **\"Đã đồng ý hình ảnh\"** + link **\"Thu hồi đồng ý\"** — bấm rồi **\"Xác nhận thu hồi\"**; ảnh của con được **ẩn ngay lập tức**.\n- Có thể bật/thu hồi bất cứ lúc nào; mỗi lần thay đổi đều được hệ thống ghi nhận.\n\n### 3.3. Chỉ xem\n\n- **\"Lớp / khoá đang học\"**: danh sách lớp của con.\n- **\"Năng lực robotics\"**: 10 kỹ năng (Lắp ráp cơ khí, Tư duy thuật toán, Lập trình…) với mức mới nhất: **Cần hỗ trợ** (đỏ) / **Cơ bản** (vàng) / **Tốt** (xanh dương) / **Xuất sắc** (xanh lá).\n\n## 4. Lưu ý\n\n- Muốn xem/sửa con nào thì con đó phải là **con đang chọn** — bấm \"Xem hồ sơ\" ở thẻ con là hệ thống tự chuyển.\n- \"Tài khoản chưa được liên kết với học viên nào\" — liên hệ trung tâm để được liên kết con.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Danh sách các con | [/portal/ho-so-con](/portal/ho-so-con) |\n| Hồ sơ chi tiết con đang chọn | [/portal/ho-so-con/chi-tiet](/portal/ho-so-con/chi-tiet) |\n| Xem ảnh lớp (sau khi bật đồng ý) | [/portal/hinh-anh](/portal/hinh-anh) |\n| Vào Cổng học sinh của con | [Chip \"Phụ huynh\" góc trên trái → chọn tên con](/portal/huong-dan/cong-hoc-sinh) |"
  },
  {
    "slug": "lich-hoc",
    "order": 3,
    "title": "Lịch học",
    "category": "Theo dõi con",
    "description": "Lịch học của con đang chọn — buổi kế tiếp, tuần này, các buổi sắp tới và lịch tháng.",
    "pagePath": "/portal/lich",
    "body": "# 03. Lịch học\n\n> Trang: **Lịch học** (`/portal/lich`) — menu trái.\n\n## 1. Trang này dùng để làm gì?\n\nXem toàn bộ lịch học của **con đang chọn**: buổi học tiếp theo, lịch trong tuần, các buổi sắp tới và lịch tháng dạng lưới — kèm tóm tắt chuyên cần.\n\n## 2. Các khu vực trên trang\n\n### 2.1. Dải đầu trang\n\nTên con · khóa · lớp + 3 ô: **Chuyên cần 〈%〉** · **Đã học 〈x〉/〈tổng〉** · **Còn lại 〈n〉**.\n\n### 2.2. \"Buổi học tiếp theo\"\n\nTên buổi (\"Buổi 〈n〉: 〈tên bài〉\") + badge **\"Hôm nay\"** (nếu đúng hôm nay) hoặc ngày + giờ học + phòng/giáo viên.\n\n### 2.3. \"Lịch học tuần này\"\n\nTừng ngày trong tuần có buổi học: thứ + ngày, tên buổi, giờ · phòng · giáo viên, badge \"Hôm nay\"/\"Sắp tới\".\n\n### 2.4. \"Các buổi học sắp tới\"\n\nTối đa 8 buổi kế: số thứ tự + tên bài + \"Dự kiến: 〈ngày〉\"; buổi gần nhất có badge **\"Đang học\"**.\n\n### 2.5. \"Lịch tháng\"\n\nLưới tháng — ngày hôm nay tô cam, mỗi ô hiện các buổi (tên lớp + giờ). Chuyển tháng bằng nút **‹ / ›**.\n\n## 3. Lưu ý\n\n- Lịch theo **con đang chọn** — nhà nhiều con thì đổi con bằng chip góc trên trái.\n- Buổi bị trung tâm hủy không hiển thị; ngày nghỉ lễ lịch tự dời theo thông báo của trung tâm.\n- Con học nhiều lớp: phần \"buổi kế / tuần này / sắp tới\" theo lớp chính đang học; **lịch tháng** gộp đủ mọi lớp.\n- \"Chưa có lịch học.\" — con chưa được xếp lớp; liên hệ trung tâm.\n- Con vắng buổi nào cần học bù → xem trang **Yêu cầu** để đăng ký học bù.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Xem lịch học | [/portal/lich](/portal/lich) |\n| Đăng ký học bù buổi vắng | [/portal/yeu-cau](/portal/yeu-cau) |\n| Xem điểm danh/chuyên cần chi tiết | [/portal/hoc-ba](/portal/hoc-ba) |"
  },
  {
    "slug": "nhan-xet",
    "order": 4,
    "title": "Nhận xét của giáo viên",
    "category": "Theo dõi con",
    "description": "Đọc nhận xét chi tiết giáo viên viết cho con sau từng buổi học.",
    "pagePath": "/portal/nhan-xet",
    "body": "# 04. Nhận xét của giáo viên\n\n> Trang: **Nhận xét** (`/portal/nhan-xet`) — menu trái.\n\n## 1. Trang này dùng để làm gì?\n\nĐọc **nhận xét giáo viên viết cho con sau từng buổi học** — kênh chính để biết hôm nay con học gì, thái độ và tiến bộ ra sao. Khi giáo viên lưu nhận xét mới, phụ huynh cũng nhận được thông báo (chuông 🔔 + email).\n\n## 2. Cách dùng\n\n1. Nhà nhiều con: chọn con ở dòng **\"Đang xem con:\"** đầu trang.\n2. **Danh sách bên trái**: các buổi có nhận xét (mới nhất trước) — số buổi, tên bài học, ngày · tên giáo viên. Buổi đang chọn tô nền cam.\n3. **Bên phải — \"Báo cáo buổi học\"**: tên buổi, ngày, giáo viên, lớp, và phần **\"Nhận xét của giáo viên\"** đầy đủ.\n\n💡 Trang hiển thị tối đa 20 nhận xét gần nhất. Ô tìm kiếm và các bộ lọc phía trên hiện mang tính giao diện — cứ chọn trực tiếp buổi trong danh sách bên trái.\n\n## 3. Lưu ý\n\n- Nhận xét theo **con đang chọn**.\n- \"Chưa có nhận xét nào.\" — con chưa có buổi nào được giáo viên nhận xét (thường có sau mỗi buổi học).\n- Muốn trao đổi thêm với giáo viên về nhận xét → dùng trang **Tin nhắn**.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Đọc nhận xét | [/portal/nhan-xet](/portal/nhan-xet) |\n| Nhắn tin với giáo viên | [/portal/tin-nhan](/portal/tin-nhan) |\n| Xem thông báo nhận xét mới | [/portal/thong-bao](/portal/thong-bao) |"
  },
  {
    "slug": "hinh-anh-lop",
    "order": 5,
    "title": "Hình ảnh lớp",
    "category": "Theo dõi con",
    "description": "Xem ảnh hoạt động của con tại lớp theo từng buổi — cần bật đồng ý dùng hình ảnh trước.",
    "pagePath": "/portal/hinh-anh",
    "body": "# 05. Hình ảnh lớp\n\n> Trang: **Hình ảnh lớp** (`/portal/hinh-anh`) — menu trái.\n\n## 1. Trang này dùng để làm gì?\n\nXem **ảnh hoạt động của con tại lớp**, nhóm theo từng buổi học (tên buổi + ngày chụp + chú thích). Ảnh do giáo viên đăng và **đã được trung tâm duyệt** mới hiển thị tới phụ huynh.\n\n## 2. Điều kiện xem ảnh (quan trọng)\n\nẢnh chỉ hiển thị khi **đủ 3 điều kiện**:\n\n1. Phụ huynh đã **bật đồng ý dùng hình ảnh** cho con (trong Hồ sơ chi tiết của con).\n2. Ảnh đã được **trung tâm duyệt**.\n3. Ảnh thuộc lớp con đang học (ảnh chung cả lớp, hoặc ảnh con được gắn thẻ).\n\nNếu chưa bật đồng ý, trang hiện: *\"Cần bật đồng ý dùng hình ảnh cho con thì mới xem được ảnh lớp. Bạn có thể thu hồi bất cứ lúc nào.\"* + nút **\"Bật đồng ý trong Hồ sơ con\"** — bấm để sang trang bật.\n\n## 3. Cách dùng\n\n1. Nhà nhiều con: chọn con ở dòng **\"Đang xem con:\"**.\n2. Ảnh nhóm theo buổi: \"Buổi 〈n〉 — 〈tên bài〉 · Ngày chụp 〈ngày〉 · 〈n〉 ảnh\"; mỗi ảnh kèm chú thích của giáo viên.\n\n## 4. Lưu ý\n\n- **Thu hồi đồng ý** bất cứ lúc nào tại Hồ sơ chi tiết của con — ảnh của con được **ẩn ngay lập tức**.\n- Ảnh của học viên khác (không phải con mình) không bao giờ hiển thị cho bạn — thiết kế bảo mật.\n- \"Chưa có ảnh lớp nào.\" — giáo viên chưa đăng hoặc ảnh chưa được duyệt; ảnh thường lên sau buổi học 1–2 ngày.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Xem ảnh lớp | [/portal/hinh-anh](/portal/hinh-anh) |\n| Bật/thu hồi đồng ý dùng hình ảnh | [/portal/ho-so-con/chi-tiet](/portal/ho-so-con/chi-tiet) |"
  },
  {
    "slug": "hoc-ba",
    "order": 6,
    "title": "Học bạ",
    "category": "Theo dõi con",
    "description": "Học bạ điện tử của con — bản chính thức đã phát hành và bản tổng hợp tạm tính; in / tải PDF.",
    "pagePath": "/portal/hoc-ba",
    "body": "# 06. Học bạ\n\n> Trang: **Học bạ** (`/portal/hoc-ba`) — menu trái.\n\n## 1. Trang này dùng để làm gì?\n\nXem **học bạ điện tử** của con đang chọn: thông tin chung, chuyên cần, nhận xét tổng kết — có thể **in** hoặc **tải PDF**.\n\n## 2. Hai loại học bạ (quan trọng)\n\n| Loại | Ý nghĩa |\n|---|---|\n| **\"Học bạ chính thức\"** | Bản đã được trung tâm **phát hành** — số liệu chốt tại ngày phát hành, có \"Ngày phát hành\" |\n| **\"Bản tổng hợp tạm tính\"** | Chưa có bản phát hành — hệ thống tổng hợp tạm từ dữ liệu học tập hiện có, thay đổi theo thời gian |\n\nDải thông báo đầu trang luôn ghi rõ đang xem loại nào.\n\n## 3. Nội dung học bạ\n\n- **\"Thông tin chung\"**: học viên, mã học viên, lớp, khóa học, giáo viên (+ ngày phát hành nếu là bản chính thức).\n- **\"Chuyên cần\"**: vòng tròn % + Tổng buổi · Có mặt/Đã học · Vắng/Còn lại. (Buổi vắng **đã học bù** được tính như có mặt.)\n- **\"Nhận xét tổng kết\"** của giáo viên (nếu có).\n- **\"Học bạ đã phát hành trước đó\"**: các bản cũ của những khóa trước — vẫn tải PDF được.\n\n## 4. In / tải PDF\n\n- **\"In học bạ\"** — mở hộp thoại in của trình duyệt.\n- **\"Tải PDF\"** — tải bản PDF (bản chính thức tải đúng bản đã phát hành; bản tạm tính tải bảng điểm hiện tại).\n\n## 5. Lưu ý\n\n- Học bạ theo **con đang chọn**; nhà nhiều con đổi con ở dòng \"Đang xem con:\".\n- Học bạ giáo viên đang soạn/chờ duyệt **không hiển thị** — chỉ bản đã phát hành mới là chính thức.\n- \"Lớp chưa bắt đầu / chưa có dữ liệu chuyên cần\" — lớp mới, số liệu sẽ cập nhật sau buổi đầu tiên (không phải con vắng).\n- \"Chưa có dữ liệu học bạ cho học viên này.\" — con chưa vào lớp hoặc chưa có dữ liệu.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Xem học bạ | [/portal/hoc-ba](/portal/hoc-ba) |\n| Xem kết quả bài thi/bài tập chi tiết | [/portal/ket-qua](/portal/ket-qua) |\n| Đọc nhận xét từng buổi | [/portal/nhan-xet](/portal/nhan-xet) |"
  },
  {
    "slug": "hoc-phi",
    "order": 7,
    "title": "Học phí & công nợ",
    "category": "Học phí & yêu cầu",
    "description": "Xem học phí đã đóng, công nợ còn lại, kỳ đến hạn và các phiếu thu đã xác nhận.",
    "pagePath": "/portal/hoc-phi",
    "body": "# 07. Học phí & công nợ\n\n> Trang: **Học phí & công nợ** (`/portal/hoc-phi`) — menu trái.\n\n## 1. Trang này dùng để làm gì?\n\nXem **học phí của con đang chọn**: số đã đóng, công nợ còn lại, kỳ đến hạn và danh sách phiếu thu. Trang **chỉ để xem** — không có thanh toán online; mọi giao dịch thực hiện tại trung tâm (trang có sẵn số hotline để liên hệ).\n\n## 2. Nguyên tắc hiển thị (đọc trước)\n\n- Chỉ hiển thị các khoản **kế toán đã xác nhận thực thu**. Khoản vừa nộp mà kế toán chưa xác nhận sẽ **chưa** cộng vào \"Đã thanh toán\" — trang có dòng báo \"Có N khoản đang chờ kế toán xác nhận…\".\n- **Công nợ = giá phải đóng − số đã xác nhận**, tính riêng theo từng khóa học của con.\n\n## 3. Các khu vực trên trang\n\n1. **3 ô số liệu**: 🟢 **\"Đã thanh toán (đã xác nhận)\"** · 🟡 **\"Công nợ còn lại\"** · 🔴 **\"Kỳ đến hạn\"** (ngày, hoặc \"—\" nếu hết nợ).\n2. **\"Khoản cần thanh toán\"**: từng khóa còn nợ — badge đỏ **\"Chưa thanh toán\"**, số tiền, và dòng \"Hạn đóng: 〈ngày〉 (còn N ngày / quá hạn N ngày)\". Kèm nhắc: liên hệ hotline trung tâm để được hướng dẫn thanh toán. Khi hết nợ: dải xanh **\"Đã thanh toán đủ — không có khoản nào cần đóng.\"**\n3. **\"Phiếu thu đã xác nhận\"**: từng phiếu — mã đơn, ngày, phương thức (Tiền mặt / Chuyển khoản / VNPAY…), số tiền, badge xanh **\"Đã xác nhận\"**.\n\n## 4. Lưu ý\n\n- Học phí theo **con đang chọn** — nhà nhiều con đổi con ở dòng \"Đang xem con:\".\n- Nếu thấy \"Có N khoản bị từ chối — vui lòng liên hệ trung tâm\" — một khoản ghi nhận có vấn đề, gọi hotline để đối soát.\n- \"Chưa có phiếu thu nào được xác nhận.\" — chưa có giao dịch nào được kế toán xác nhận.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Xem học phí & công nợ | [/portal/hoc-phi](/portal/hoc-phi) |\n| Xem thông báo học phí | [/portal/thong-bao](/portal/thong-bao) |\n| Hỏi đáp về học phí | [/portal/yeu-cau](/portal/yeu-cau) |"
  },
  {
    "slug": "yeu-cau",
    "order": 8,
    "title": "Gửi yêu cầu (báo vắng, học bù…)",
    "category": "Học phí & yêu cầu",
    "description": "Gửi 6 loại yêu cầu tới trung tâm — báo vắng, xin học bù, chuyển lớp/cơ sở, bảo lưu, khác — và theo dõi phản hồi.",
    "pagePath": "/portal/yeu-cau",
    "body": "# 08. Gửi yêu cầu (báo vắng, học bù…)\n\n> Trang: **Yêu cầu học bù** (`/portal/yeu-cau`) — menu trái.\n\n## 1. Trang này dùng để làm gì?\n\nLà kênh **gửi yêu cầu chính thức** tới trung tâm cho con đang chọn: báo vắng, xin học bù, chuyển lớp, chuyển cơ sở, bảo lưu và yêu cầu khác. Đồng thời theo dõi **các buổi con cần học bù** và **phản hồi của trung tâm** cho từng yêu cầu.\n\n## 2. Buổi cần học bù\n\n- Đầu trang có 3 ô: 🟡 **\"Buổi cần học bù\"** · 🔵 **\"Đã xếp buổi bù\"** · 🟢 **\"Đã học bù\"**.\n- Mục **\"Buổi cần học bù\"**: mỗi buổi con vắng chưa bù là một thẻ vàng — bấm **\"Gửi yêu cầu học bù\"** là form bên dưới tự chọn loại \"Xin học bù\" và điền sẵn nội dung buổi vắng.\n- **Chính sách học bù**: học bù đúng nội dung buổi đã vắng; **được học bù liên cơ sở** (ưu tiên cơ sở của con); yêu cầu cần trung tâm duyệt trước khi học.\n\n## 3. Gửi yêu cầu mới (từng bước)\n\n1. Kéo tới mục **\"Gửi yêu cầu mới\"**.\n2. Chọn **loại yêu cầu**:\n\n| Loại | Dùng khi |\n|---|---|\n| **Báo vắng** (mặc định) | Xin nghỉ trước một buổi học — chọn thêm **\"Buổi xin vắng\"** trong danh sách buổi sắp tới |\n| **Xin học bù** | Xin bù buổi đã vắng (có thể kèm \"Ngày liên quan\") |\n| **Chuyển lớp** | Xin đổi lớp trong cùng khóa |\n| **Chuyển cơ sở** | Xin chuyển cơ sở học |\n| **Bảo lưu** | Xin tạm dừng học (kèm ngày dự kiến) |\n| **Khác** | Hỏi đáp, khiếu nại, yêu cầu khác |\n\n3. Nhập **mô tả chi tiết** (tối thiểu 5 ký tự).\n4. Bấm **\"Gửi yêu cầu\"** → thông báo **\"Đã gửi yêu cầu\"** — trung tâm (tư vấn/quản lý cơ sở) nhận được ngay.\n\n💡 Báo vắng nhớ **chọn đúng buổi** — thiếu sẽ báo \"Vui lòng chọn buổi xin vắng\". Hệ thống giới hạn tối đa 10 yêu cầu đang chờ cùng lúc và 5 yêu cầu/10 phút.\n\n## 4. Theo dõi & hủy yêu cầu\n\nMục **\"Yêu cầu đã gửi\"** liệt kê từng yêu cầu với trạng thái:\n\n| Badge | Ý nghĩa |\n|---|---|\n| 🟡 **\"Chờ xử lý\"** | Trung tâm chưa xử lý — còn **hủy được** |\n| 🟢 **\"Đã duyệt\"** | Được chấp thuận; đọc dòng **\"Phản hồi: …\"** |\n| 🔴 **\"Từ chối\"** | Không được chấp thuận — xem lý do ở phần phản hồi |\n| ⚪ **\"Đã huỷ\"** | Do bạn tự hủy |\n\n- **Hủy**: bấm **\"Huỷ\"** → nút đổi đỏ \"Bấm lần nữa để huỷ\" → bấm lần 2 → \"Đã huỷ yêu cầu\". Chỉ hủy được khi còn \"Chờ xử lý\".\n- Trạng thái học bù ở mục lịch sử: **\"Chờ xếp buổi\"** → **\"Đã xếp buổi bù\"** → **\"Đã học bù\"**.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Gửi yêu cầu / xem học bù | [/portal/yeu-cau](/portal/yeu-cau) |\n| Xem lịch trước khi báo vắng | [/portal/lich](/portal/lich) |\n| Trao đổi nhanh với giáo viên | [/portal/tin-nhan](/portal/tin-nhan) |"
  },
  {
    "slug": "thong-bao",
    "order": 9,
    "title": "Thông báo",
    "category": "Liên lạc & khảo sát",
    "description": "Bảng tin tổng hợp — nhận xét, lịch học, học bù, học phí, học bạ, khảo sát và thông báo từ trung tâm.",
    "pagePath": "/portal/thong-bao",
    "body": "# 09. Thông báo\n\n> Trang: **Thông báo** (`/portal/thong-bao`) — menu trái, hoặc bấm **chuông 🔔** trên thanh trên cùng.\n\n## 1. Trang này dùng để làm gì?\n\nLà **bảng tin tổng hợp** mọi cập nhật liên quan đến các con: nhận xét mới của giáo viên, thay đổi lịch học, học bù, học phí, học bạ, khảo sát và thông báo chung từ trung tâm — gom về một chỗ, lọc được theo loại.\n\n## 2. Cách dùng\n\n1. Mở trang — thông báo chia 2 khu: **\"Mới\"** (viền trái đậm màu, khoảng 2 ngày gần nhất) và **\"Trước đó\"**.\n2. **Lọc theo loại** bằng dải nút (mặc định **\"Tất cả\"**): Nhận xét · Trung tâm · Lịch học · Học bù · Học phí · Học bạ · Khảo sát. Mỗi nút có số đếm thông báo mới của loại đó.\n3. **Bấm vào một thông báo** → đi thẳng tới trang liên quan:\n\n| Loại thông báo | Bấm vào đi đâu |\n|---|---|\n| Nhận xét | Trang Nhận xét |\n| Lịch học | Trang Lịch học |\n| Học bù | Trang Yêu cầu |\n| Học phí | Trang Học phí |\n| Học bạ | Trang Học bạ |\n| Khảo sát | Trang Khảo sát |\n| **Trung tâm** | Chỉ đọc tại chỗ (không có trang đích) |\n\n- Thông báo gửi riêng cho một con có **badge tên con**; thời gian hiển thị kiểu \"Vừa xong\" / \"3 giờ trước\" / \"2 ngày trước\".\n\n## 3. Lưu ý\n\n- Bảng tin **gộp tất cả các con** — không cần đổi con để xem.\n- Số đỏ trên **chuông 🔔** ở thanh trên = tổng thông báo mới ở đây (cập nhật mỗi ~1 phút, có thể lệch nhẹ trong chốc lát).\n- Chưa có nút \"đánh dấu đã đọc\" — mục tự chuyển xuống \"Trước đó\" sau khoảng 2 ngày.\n- \"Không có thông báo mới.\" — mọi thứ đã được cập nhật.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Xem thông báo | [/portal/thong-bao](/portal/thong-bao) |\n| Xem nhận xét của giáo viên | [/portal/nhan-xet](/portal/nhan-xet) |\n| Xem học phí | [/portal/hoc-phi](/portal/hoc-phi) |"
  },
  {
    "slug": "tin-nhan",
    "order": 10,
    "title": "Tin nhắn",
    "category": "Liên lạc & khảo sát",
    "description": "Nhắn tin 2 chiều với giáo viên phụ trách lớp của con — tách luồng theo từng lớp.",
    "pagePath": "/portal/tin-nhan",
    "body": "# 10. Tin nhắn\n\n> Trang: **Tin nhắn** (`/portal/tin-nhan`) — menu trái.\n\n## 1. Trang này dùng để làm gì?\n\nKênh **nhắn tin trực tiếp giữa phụ huynh và giáo viên phụ trách lớp** của con. Mỗi lớp con đang học là một luồng hội thoại riêng; nhà có nhiều con thì thấy đủ luồng của mọi con.\n\n## 2. Cách dùng\n\n1. **Cột trái**: danh sách các lớp đang học của các con — bấm chọn một lớp để mở hội thoại. Lớp có **số đỏ** = có tin của giáo viên chưa đọc; mở luồng là tự đánh dấu đã đọc.\n2. **Cột phải**: nội dung hội thoại — tin của mình nằm **bên phải (bong bóng cam, nhãn \"Bạn\")**, tin của giáo viên **bên trái (nhãn \"Giáo viên\")**, kèm giờ gửi. Con từng chuyển lớp thì lịch sử vẫn liền mạch, mỗi tin có nhãn tên lớp.\n3. **Gửi tin**: gõ vào ô \"Nhập tin nhắn gửi giáo viên…\" (tối đa 2000 ký tự) → bấm **\"Gửi\"** (hoặc phím **Ctrl + Enter**). Giáo viên phụ trách lớp nhận được thông báo ngay.\n\n## 3. Lưu ý\n\n- Chỉ nhắn được với lớp **đang học** (lớp đã kết thúc không hiện trong danh sách, nhưng lịch sử tin vẫn giữ).\n- Tin trống sẽ báo \"Vui lòng nhập nội dung\"; đang gửi nút hiện \"Đang gửi…\".\n- Việc khẩn (xin nghỉ, đổi lịch, khiếu nại) nên gửi qua trang **Yêu cầu** để được xử lý theo quy trình — tin nhắn phù hợp cho trao đổi thông thường với giáo viên.\n- \"Hiện chưa có lớp đang học nào để trao đổi.\" — con chưa vào lớp; liên hệ trung tâm nếu cần.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Nhắn tin với giáo viên | [/portal/tin-nhan](/portal/tin-nhan) |\n| Gửi yêu cầu chính thức tới trung tâm | [/portal/yeu-cau](/portal/yeu-cau) |"
  },
  {
    "slug": "khao-sat",
    "order": 11,
    "title": "Khảo sát trung tâm",
    "category": "Liên lạc & khảo sát",
    "description": "Trả lời khảo sát đánh giá trung tâm/cơ sở — mỗi khảo sát chỉ gửi một lần, tổng hợp ẩn danh.",
    "pagePath": "/portal/khao-sat",
    "body": "# 11. Khảo sát trung tâm\n\n> Trang: **Khảo sát trung tâm** (`/portal/khao-sat`) — menu trái.\n\n## 1. Trang này dùng để làm gì?\n\nNơi phụ huynh trả lời các **khảo sát đánh giá trung tâm/cơ sở** (chất lượng giảng dạy, cơ sở vật chất, dịch vụ). Mọi câu trả lời được **tổng hợp ẩn danh**; mỗi khảo sát chỉ gửi **một lần**.\n\n## 2. Cách làm khảo sát\n\n1. Nhà nhiều con: chọn con ở dòng **\"Đang xem con:\"** đầu trang (khảo sát tính theo từng con).\n2. Mỗi khảo sát là một thẻ với badge: 🟡 **\"Chưa làm\"** / 🟢 **\"Đã làm\"**. Số \"Chưa làm\" tổng hiện ở dải đầu trang.\n3. Bấm **\"Làm khảo sát\"** — form mở ngay trong thẻ:\n   - Câu **chấm điểm 0–10** (mức độ sẵn sàng giới thiệu Sata Robo) hoặc **1–5**, câu **chọn đáp án**, câu **nhập ý kiến**. Câu có dấu **\\*** đỏ là bắt buộc.\n   - Ô **\"Góp ý thêm (tuỳ chọn)…\"** ở cuối.\n4. Bấm **\"Gửi khảo sát\"** → thông báo **\"Cảm ơn đánh giá của quý phụ huynh!\"** — thẻ chuyển sang \"Đã hoàn thành\".\n\nNgoài ra có thể có khu **\"Khảo sát cơ sở đang mở\"** (đợt khảo sát lớn của cơ sở): câu hỏi dạng 5 sao / chọn một / chọn nhiều / nhập ý kiến; mỗi phụ huynh làm **một lần cho mỗi đợt**.\n\n## 3. Thông báo có thể gặp\n\n- \"Vui lòng trả lời: 〈câu hỏi〉\" / \"Vui lòng chọn điểm 0–10\" — còn câu bắt buộc chưa trả lời.\n- \"Bạn đã trả lời khảo sát này rồi.\" — mỗi khảo sát chỉ gửi một lần cho mỗi con.\n- \"Khảo sát không tồn tại hoặc đã đóng.\" — đợt khảo sát đã hết hạn.\n- \"Hiện chưa có khảo sát nào đang mở.\" — không có khảo sát cần trả lời.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Làm khảo sát | [/portal/khao-sat](/portal/khao-sat) |\n| Xem thông báo có khảo sát mới | [/portal/thong-bao](/portal/thong-bao) |"
  },
  {
    "slug": "cong-hoc-sinh",
    "order": 12,
    "title": "Cổng học sinh — chuyển chế độ & tổng quan",
    "category": "Cổng học sinh",
    "description": "Cách vào Cổng học sinh của từng con; trang tổng quan, lịch học và thông báo dành cho con.",
    "pagePath": "/portal/hoc-sinh",
    "body": "# 12. Cổng học sinh — chuyển chế độ & tổng quan\n\n> Khu vực: **Cổng học sinh** (`/portal/hoc-sinh`) — giao diện màu cam dành cho con tự dùng (dưới sự giám sát của phụ huynh).\n\n## 1. Cổng học sinh là gì?\n\nLà **giao diện riêng cho con**: nhìn thấy tiến độ khóa học, việc cần làm, bài tập, buổi học — và tự làm bài tập/bài thi. Menu gọn 6 mục: **Tổng quan · Lịch học · Bài tập · Buổi học · Đánh giá giáo viên · Thông báo**.\n\n## 2. Cách vào / thoát Cổng học sinh\n\n- **Vào**: bấm **chip \"PHỤ HUYNH · 〈tên〉\"** góc trên bên trái → trong mục **\"Các con\"** chọn tên con → giao diện chuyển sang Cổng học sinh (màu cam) của đúng con đó.\n- **Thoát**: bấm lại chip (giờ ghi \"HỌC SINH · 〈tên con〉\") → chọn **\"Chế độ Phụ huynh\"**.\n\n## 3. Trang Tổng quan của con (`/portal/hoc-sinh`)\n\n- **\"Chào 〈tên con〉! 🚀\"** + vòng tròn **\"Tiến độ khóa học\"** (% và số buổi đã học).\n- **4 ô số liệu**: \"Cần làm\" (số bài) · \"Buổi tiếp theo\" · \"Buổi đã học\" · \"Chuyên cần\".\n- **\"Hành trình khóa học\"**: dải chấm từng buổi — màu theo chú thích: Đã học · Học bù (xanh) · Vắng cần bù (viền đỏ) · Sắp tới · Hôm nay.\n- **\"Việc cần làm\"**: danh sách bài tập chưa nộp / bài kiểm tra chưa làm, badge 🔴 **\"Quá hạn\"** / 🟡 **\"Cần làm\"**. Bấm từng dòng (hoặc nút **\"Vào làm bài ngay\"**) để đi làm bài. Hết việc: \"Không có việc cần làm 🎉\".\n- **\"Kết quả của em\"**: các bài đã chấm với điểm (xanh ≥ 80%, vàng ≥ 50%, đỏ < 50%).\n- **\"Lớp học tiếp theo\"** + nút **\"Xem lịch học\"**.\n- **\"Kỹ năng của em\"**: thanh % 10 kỹ năng robotics.\n\n## 4. Lịch học của con (`/portal/hoc-sinh/lich`)\n\nGiống trang Lịch học của phụ huynh: buổi kế tiếp, tuần này, sắp tới, lịch tháng (chuyển tháng bằng ‹ ›).\n\n## 5. Thông báo của con (`/portal/hoc-sinh/thong-bao`)\n\nBảng tin giống trang Thông báo phụ huynh nhưng **chỉ lọc tin của con đang xem** + tin chung. Bấm từng tin để đi tới trang liên quan.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Tổng quan của con | [/portal/hoc-sinh](/portal/hoc-sinh) |\n| Bài tập của con | [/portal/hoc-sinh/bai-tap](/portal/hoc-sinh/bai-tap) |\n| Buổi học của con | [/portal/hoc-sinh/buoi-hoc](/portal/hoc-sinh/buoi-hoc) |\n| Đánh giá giáo viên | [/portal/hoc-sinh/danh-gia-gv](/portal/hoc-sinh/danh-gia-gv) |"
  },
  {
    "slug": "bai-tap-va-nop-bai",
    "order": 13,
    "title": "Bài tập & nộp bài",
    "category": "Cổng học sinh",
    "description": "Xem lộ trình bài tập theo buổi, làm bài và nộp bài bằng chữ hoặc file; xem điểm sau khi giáo viên chấm.",
    "pagePath": "/portal/hoc-sinh/bai-tap",
    "body": "# 13. Bài tập & nộp bài\n\n> Trang: **Bài tập** (`/portal/hoc-sinh/bai-tap`) — menu Cổng học sinh.\n\n## 1. Trang này dùng để làm gì?\n\nXem **lộ trình từng buổi học** của khóa và bài tập gắn với mỗi buổi; từ đây con vào **làm và nộp bài**. Bài nộp xong giáo viên chấm — điểm + nhận xét hiện lại trên cổng.\n\n## 2. Danh sách bài tập theo buổi\n\nMỗi buổi một dòng: \"Buổi 〈n〉: 〈tên bài học〉\" + ngày học; nếu buổi có bài tập thì ghi \"BT: 〈tên〉 · Hạn: 〈ngày〉\" và:\n\n| Hiển thị | Ý nghĩa |\n|---|---|\n| Nút **\"Làm bài tập\"** | Chưa làm — bấm để vào làm |\n| 🔴 **\"Quá hạn\"** | Chưa nộp và đã qua hạn — vẫn nộp được nhưng bị đánh dấu trễ |\n| 🟢 **\"Đã làm\"** + nút **\"Làm lại\"** | Đã nộp — có thể sửa lại bài trước khi giáo viên chấm |\n| \"Không có bài tập\" | Buổi này không giao bài |\n\n## 3. Làm & nộp bài (từng bước)\n\n1. Bấm **\"Làm bài tập\"** → mở trang đề bài: mô tả, **\"Hướng dẫn\"**, tài liệu đính kèm (bấm mở tab mới).\n2. Làm bài trong khối **\"Nộp bài\"**:\n   - **Gõ trực tiếp** vào ô trả lời, và/hoặc\n   - **\"Đính kèm ảnh / tài liệu\"** — nhận ảnh, PDF, Word, Excel, PowerPoint, txt.\n3. Bấm **\"Nộp bài\"** → thông báo **\"Đã nộp bài\"** (đúng hạn) hoặc **\"Đã nộp (trễ hạn)\"**.\n\n### Quy tắc cần nhớ\n\n- **Nộp lại được nhiều lần** (bài nộp mới thay bài cũ) — cho tới khi giáo viên chấm.\n- ⚠️ **Giáo viên đã chấm thì khóa** — \"Bài đã được chấm — không thể nộp lại\".\n- Sau hạn vẫn nộp được nhưng bị đánh dấu **\"Nộp trễ\"**.\n- Thiếu nội dung sẽ báo \"Nhập nội dung hoặc đính kèm file\" / \"Vui lòng đính kèm file bài làm\".\n\n## 4. Xem điểm\n\n- Khi đã chấm, mở lại bài sẽ thấy **\"Điểm: x/y\"** + **\"Nhận xét\"** (+ bảng rubric nếu giáo viên chấm theo tiêu chí).\n- Tổng hợp toàn bộ điểm: trang **Kết quả** (`/portal/ket-qua`); tình trạng: **\"Chưa nộp\"** · **\"Đã nộp\"** · **\"Nộp trễ\"** · **\"Đã chấm\"**.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Bài tập theo buổi (Cổng học sinh) | [/portal/hoc-sinh/bai-tap](/portal/hoc-sinh/bai-tap) |\n| Việc cần làm hôm nay | [/portal/hoc-sinh](/portal/hoc-sinh) |\n| Xem kết quả tổng hợp | [/portal/ket-qua](/portal/ket-qua) |\n| Xem bài giảng các buổi đã học | [/portal/bai-giang](/portal/bai-giang) |"
  },
  {
    "slug": "bai-thi-va-ket-qua",
    "order": 14,
    "title": "Bài thi & kết quả",
    "category": "Cổng học sinh",
    "description": "Vào làm bài thi có đếm giờ (tự lưu, hết giờ tự nộp) và xem điểm ở trang Kết quả.",
    "pagePath": "/portal/bai-thi",
    "body": "# 14. Bài thi & kết quả\n\n> Trang: **Bài thi** (`/portal/bai-thi`) và **Kết quả** (`/portal/ket-qua`). Bài kiểm tra chưa làm cũng hiện trong \"Việc cần làm\" ở Tổng quan Cổng học sinh.\n\n## 1. Danh sách bài thi (`/portal/bai-thi`)\n\nMỗi đề thi một dòng: tên đề · lớp · thời lượng (phút) · ngày đóng, kèm nút/badge:\n\n| Hiển thị | Ý nghĩa |\n|---|---|\n| Nút **\"Vào làm\"** | Đề đang mở, chưa làm |\n| Nút **\"Tiếp tục làm\"** (vàng) | Đang làm dở — vào làm tiếp, không mất bài |\n| **\"Điểm: 〈x〉\"** / **\"Chờ chấm\"** | Đã nộp — điểm hoặc chờ giáo viên chấm câu tự luận |\n| Nút **\"Thi lại (1/2)\"** | Còn lượt thi lại và đề còn mở |\n| **\"Chưa mở\"** | Chưa tới giờ mở đề |\n\n## 2. Làm bài thi (từng bước)\n\n1. Bấm **\"Vào làm\"** — hệ thống tính giờ từ lúc bắt đầu.\n2. Đầu trang có **đồng hồ đếm ngược** (còn ≤ 1 phút chuyển nền đỏ).\n3. Trả lời từng câu: **trắc nghiệm** (chọn nhiều) · **đúng/sai** (chọn một) · **trả lời ngắn** · **tự luận/lập trình** (giáo viên chấm tay).\n4. Bài **tự lưu liên tục** (\"Đã lưu tự động\" ở cuối trang) — lỡ tắt trang vẫn \"Tiếp tục làm\" được.\n5. Bấm **\"Nộp bài\"** khi xong → \"Đã nộp bài\". ⚠️ **Hết giờ hệ thống tự nộp** (\"Hết giờ — đã nộp bài tự động\") với các câu đã lưu.\n6. Nộp xong tự chuyển sang trang **Kết quả**.\n\n### Chấm điểm\n\n- Trắc nghiệm / đúng-sai / trả lời ngắn: **chấm tự động ngay**.\n- Câu tự luận / lập trình: **chờ giáo viên chấm** — trạng thái \"Chờ chấm\" cho tới khi có điểm.\n\n## 3. Trang Kết quả (`/portal/ket-qua`)\n\nTổng hợp toàn bộ kết quả của con:\n\n- **Năng lực robotics** (mức từng kỹ năng) + **báo cáo tiến độ mới nhất**.\n- **Tiến độ từng lớp**: điểm danh, bài học, bài tập nộp, điểm trung bình, đề thi đạt.\n- **Kết quả bài thi**: \"〈điểm〉/〈tổng〉 · Đạt/Chưa đạt\" hoặc \"Chờ giáo viên chấm\", kèm nhận xét.\n- **Kết quả bài tập**: điểm + trạng thái (Đã nộp / Nộp trễ / Đã chấm) + nhận xét.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Danh sách bài thi | [/portal/bai-thi](/portal/bai-thi) |\n| Xem kết quả | [/portal/ket-qua](/portal/ket-qua) |\n| Việc cần làm hôm nay | [/portal/hoc-sinh](/portal/hoc-sinh) |"
  },
  {
    "slug": "buoi-hoc",
    "order": 15,
    "title": "Buổi học",
    "category": "Cổng học sinh",
    "description": "Xem chi tiết từng buổi — mục tiêu buổi học, điểm danh của con và bài tập của buổi.",
    "pagePath": "/portal/hoc-sinh/buoi-hoc",
    "body": "# 15. Buổi học\n\n> Trang: **Buổi học** (`/portal/hoc-sinh/buoi-hoc`) — menu Cổng học sinh.\n\n## 1. Trang này dùng để làm gì?\n\nXem **chi tiết từng buổi học** của con: mục tiêu buổi, tình trạng điểm danh và bài tập gắn với buổi — bố cục 2 cột (danh sách buổi bên trái, chi tiết bên phải).\n\n## 2. Cách dùng\n\n1. Đầu trang có 4 ô: **\"Đã học\"** (x/tổng) · **\"Có mặt\"** · **\"Vắng\"** · **\"Đã học bù\"**.\n2. **Cột trái**: danh sách buổi (buổi đã học có dấu tích xanh). Trang tự chọn sẵn buổi **hôm nay** (hoặc buổi gần nhất đã qua).\n3. Bấm một buổi → **cột phải** hiện chi tiết:\n   - **\"Mục tiêu buổi học\"** — các gạch đầu dòng nội dung buổi.\n   - **\"Bài tập của buổi\"** — nút **\"Làm bài\"** (chưa làm) hoặc link **\"Đã làm · Xem\"**.\n   - **\"Điểm danh\"** — badge trạng thái của con.\n\n## 3. Ý nghĩa badge điểm danh\n\n| Badge | Ý nghĩa |\n|---|---|\n| 🟢 **\"Có mặt\"** | Con đi học buổi này |\n| 🟡 **\"Vắng có phép\"** | Vắng có xin phép |\n| 🔴 **\"Vắng\"** | Vắng — nên đăng ký học bù ở trang Yêu cầu |\n| 🔵 **\"Học bù\"** | Buổi vắng đã được học bù |\n| ⚪ **\"Chưa diễn ra\"** | Buổi tương lai |\n| **\"Hôm nay\"** | Buổi diễn ra hôm nay |\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Chi tiết buổi học | [/portal/hoc-sinh/buoi-hoc](/portal/hoc-sinh/buoi-hoc) |\n| Làm bài tập của buổi | [/portal/hoc-sinh/bai-tap](/portal/hoc-sinh/bai-tap) |\n| Đăng ký học bù buổi vắng | [/portal/yeu-cau](/portal/yeu-cau) |"
  },
  {
    "slug": "danh-gia-giao-vien",
    "order": 16,
    "title": "Đánh giá giáo viên",
    "category": "Cổng học sinh",
    "description": "Con đánh giá thầy/cô theo đợt đang mở — chọn sao, chọn đáp án, gửi lời nhắn; hoàn toàn ẩn danh.",
    "pagePath": "/portal/hoc-sinh/danh-gia-gv",
    "body": "# 16. Đánh giá giáo viên\n\n> Trang: **Đánh giá giáo viên** (`/portal/hoc-sinh/danh-gia-gv`) — menu Cổng học sinh.\n\n## 1. Trang này dùng để làm gì?\n\nKhi trung tâm mở **đợt đánh giá**, con (cùng phụ huynh) đánh giá các thầy/cô đang dạy mình: chấm sao, chọn đáp án, viết lời nhắn. Câu trả lời được giữ **bí mật (ẩn danh)** — thầy/cô không biết ai đánh giá.\n\n## 2. Cách đánh giá (từng bước)\n\n1. Mở trang — mỗi đợt đánh giá là một khu, bên trong mỗi thầy/cô một phiếu (\"Thầy/cô 〈tên〉 · 〈lớp〉\").\n2. Trả lời các câu hỏi:\n   - **Chấm sao** ★ (1–5).\n   - **Chọn đáp án** (thẻ to, có emoji dễ thương).\n   - **Chọn nhiều** (ô tick).\n   - **Viết lời nhắn** (ô nhập, tối đa 2000 ký tự).\n   - Câu có dấu **\\*** đỏ là bắt buộc.\n3. Bấm **\"Gửi đánh giá\"** → thông báo **\"Cảm ơn em đã đánh giá!\"** — phiếu chuyển thành hộp xanh xác nhận.\n\n## 3. Lưu ý\n\n- Mỗi thầy/cô chỉ đánh giá **một lần trong một đợt** — gửi rồi phiếu không hiện lại.\n- \"Hiện chưa có đợt đánh giá nào đang mở. Cảm ơn em! 🌟\" — trung tâm chưa mở đợt; quay lại khi có thông báo.\n- \"Đợt đánh giá đã đóng hoặc chưa mở\" — đợt đã hết hạn.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Đánh giá giáo viên | [/portal/hoc-sinh/danh-gia-gv](/portal/hoc-sinh/danh-gia-gv) |\n| Phụ huynh làm khảo sát trung tâm | [/portal/khao-sat](/portal/khao-sat) |"
  },
  {
    "slug": "ho-so-lien-lac",
    "order": 17,
    "title": "Hồ sơ liên lạc & đổi mật khẩu",
    "category": "Tài khoản",
    "description": "Cập nhật thông tin liên hệ của gia đình (2 phụ huynh), đổi mật khẩu, xem các con liên kết.",
    "pagePath": "/portal/ho-so",
    "body": "# 17. Hồ sơ liên lạc & đổi mật khẩu\n\n> Trang: **Hồ sơ** (`/portal/ho-so`) — menu trái, hoặc **avatar góc phải → \"Hồ sơ liên lạc\"**.\n\n## 1. Trang này dùng để làm gì?\n\nQuản lý **thông tin liên hệ của gia đình** (phụ huynh đại diện + phụ huynh thứ hai), **đổi mật khẩu**, và xem danh sách **các con liên kết** với tài khoản.\n\n## 2. Cập nhật thông tin liên hệ\n\n### Khối \"Phụ huynh đại diện\" (góc phải có **Mã hộ SATAFAM-…**)\n\n| Trường | Sửa được? |\n|---|---|\n| **Họ và tên** | ✅ |\n| **Số điện thoại** | ✅ |\n| **Email (đăng nhập & nhận báo cáo)** | ❌ Khóa — là tài khoản đăng nhập |\n| **Địa chỉ liên hệ** | ✅ |\n\n### Khối \"Phụ huynh thứ hai (tùy chọn)\"\n\n**Họ và tên** + **Số điện thoại** — điền để trung tâm liên hệ được cả bố lẫn mẹ.\n\n→ Bấm **\"Lưu hồ sơ\"** → thông báo **\"Đã lưu hồ sơ\"**. Thông tin này dùng để đối soát danh tính khi xin học bù và nhận thông báo — áp dụng chung cho **tất cả các con** trong hộ.\n\n## 3. Đổi mật khẩu\n\n1. Kéo tới khối **\"Đổi mật khẩu\"**.\n2. Nhập **\"Mật khẩu hiện tại\"** → **\"Mật khẩu mới\"** (tối thiểu 8 ký tự) → **\"Xác nhận mật khẩu\"**.\n3. Bấm **\"Cập nhật mật khẩu\"** → **\"Đã đổi mật khẩu\"**.\n\nLỗi thường gặp: \"Mật khẩu hiện tại không đúng\" · \"Mật khẩu mới tối thiểu 8 ký tự\" · \"Xác nhận mật khẩu không khớp\".\n\n## 4. \"Học sinh liên kết\"\n\nCột phải liệt kê các con: tên, lớp, badge **\"Đang chọn\"** (con đang xem), trạng thái đồng ý hình ảnh (**\"Đã đồng ý sử dụng hình ảnh\"** xanh / **\"Chưa đồng ý hình ảnh\"** vàng), và nút **\"Xem hồ sơ chi tiết\"** (tự chuyển con đó thành con đang chọn).\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Hồ sơ liên lạc | [/portal/ho-so](/portal/ho-so) |\n| Hồ sơ chi tiết của con | [/portal/ho-so-con/chi-tiet](/portal/ho-so-con/chi-tiet) |\n| Tùy chỉnh giao diện | [/portal/giao-dien](/portal/giao-dien) |\n| Bộ hướng dẫn sử dụng | [/portal/huong-dan](/portal/huong-dan) |"
  },
  {
    "slug": "giao-dien",
    "order": 18,
    "title": "Giao diện (Sáng/Tối & màu nhấn)",
    "category": "Tài khoản",
    "description": "Đổi chế độ Sáng/Tối/Hệ thống và màu nhấn riêng cho cổng phụ huynh và cổng học sinh.",
    "pagePath": "/portal/giao-dien",
    "body": "# 18. Giao diện (Sáng/Tối & màu nhấn)\n\n> Trang: **Giao diện** (`/portal/giao-dien`) — avatar góc phải → **\"Giao diện\"**.\n\n## 1. Trang này dùng để làm gì?\n\nTùy chỉnh **chế độ hiển thị** (Sáng/Tối/Hệ thống) và **màu nhấn** của cổng — chỉnh riêng được cho vai trò **Phụ huynh** và **Học sinh**. Cài đặt lưu **trên thiết bị này** (đổi máy/trình duyệt khác sẽ không mang theo).\n\n## 2. Cách dùng\n\n1. **\"Áp dụng cho:\"** — chọn đang chỉnh cho **\"Phụ huynh\"** hay **\"Học sinh\"** (mỗi vai trò một màu riêng; Sáng/Tối dùng chung).\n2. **\"Chế độ hiển thị\"**: bấm **\"Sáng\"** / **\"Tối\"** / **\"Hệ thống\"** — **áp dụng ngay** khi bấm.\n3. **\"Màu nhấn thương hiệu\"**: chọn nhanh — Tím · Cam · San hô · Xanh ngọc · Xanh lá · Chàm.\n4. **\"Tùy chỉnh màu\"**: chọn màu tự do hoặc nhập mã HEX; hệ thống có **kiểm tra độ tương phản** (báo vàng nếu màu khó đọc — nên chọn màu đậm/nhạt hơn). Nút **\"Mặc định\"** đưa về màu gốc (Phụ huynh = Tím, Học sinh = Cam).\n5. Xem thử ở ô **\"Xem trước\"** bên phải → bấm **\"Lưu thay đổi\"** (màu chỉ áp dụng sau khi lưu; **\"Hoàn tác\"** để bỏ thay đổi chưa lưu).\n\n💡 Nút **Sáng/Tối nhanh** trên thanh trên cùng dùng chung cơ chế với trang này.\n\n## 3. Lưu ý\n\n- Sáng/Tối lưu **ngay khi bấm**; màu nhấn chỉ lưu khi bấm **\"Lưu thay đổi\"**.\n- Cài đặt theo **từng thiết bị/trình duyệt** — xóa dữ liệu duyệt web sẽ về mặc định.\n- Màu chỉ đổi trong cổng phụ huynh/học sinh, không ảnh hưởng nơi khác.\n\n## Đường dẫn nhanh\n\n| Việc cần làm | Mở trang |\n|---|---|\n| Tùy chỉnh giao diện | [/portal/giao-dien](/portal/giao-dien) |\n| Hồ sơ liên lạc | [/portal/ho-so](/portal/ho-so) |"
  }
];
